---
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: brewz
spec:
  host: brewz.f5demo.com
  upstreams:
    - name: spa
      service: spa
      port: 80
    - name: api
      service: api
      port: 8000
    - name: spa-dark
      service: spa-dark
      port: 80
  routes:
    - path: /
      matches:
        - conditions:
          - cookie: "app_version"
            value: "dark"
          action:
            pass: spa-dark
      action:
        pass: spa
    - path: /api
      policies:
        - name: rate-limit-policy
      action:
        pass: api
    - path: /images
      action:
        proxy:
          upstream: api
          rewritePath: /images
